### ISSUE TITLE
APP FEATURES

### ISSUE THREAD

**Issue by obonobo** [atmos-sphere/proto#6]
- [ ] background video (#3) (@JustinLohKingWei)
- [ ] background music (#4) (@mckenzietsean)
- [ ] discover new spheres view (#5) (@instamine)
    - a view where you can find new spheres that you are not subscribed to, or are not a member of 
- [ ] subscription/"become member" for a sphere (@nuzurie)
    - Offer some way to join a sphere - by subscribing or becoming a member of that sphere
    - The sphere that you have subscribed to or favourited or whatever will be viewable in a more convenient way such as inside a sidebar with shortcuts to jump into those spheres (discord style - basically the sphere are discord servers)
- [ ] Overlay with timeout/inactivity that makes it disappear. (@obonobo)
    - Make an overlay component that contains all the UI elements: chat, sidebars, mute button, all UI stuff
    - The UI overlay can fade away when the user is not active (like the UI controls of a youtube video). The user becomes inactive when there is no mouse movement or keyboard presses for a specified duration of time, or when the tab containing the app become no longer in focus. 
- [ ] Chat component (@amneet270)
    - Make a minimizable chat component that goes in the overlay
    - If the chat is opened and active, then the UI will not fade even if the user becomes inactive.
- [ ] Some kind of UI view/page/dialog where you can configure the settings for a sphere i.e. change the music playlist, change the background, etc.
